### ISSUE TITLE
iOS Safari CVV form rendering issue

### ISSUE THREAD

**Issue by thatkahunaguy** [spreedly/sample-payment-frame#1]
Not sure if your example is intended to be responsive but the payment details in the iframe don't render properly in iOS Safari.  The CVV label and entry box sit right on top of the Expiration Date label and Month entry box.  Thinking about testing a spreedly integration and just thought I'd let you know since many customers would likely love to have a sample app that renders well on mobile.  All the other fields look fine and the service looks very interesting.

Used your herokuapp.com link, iPhone 6, iOS 8.1 and refreshed several times with the issue recurring each time.

**Comment by rwdaigle** [comment]
@thatkahunaguy thank you for this.

You're correct, we didn't spend much time on this sample app making it mobile friendly. But, we should. We'll look to make some adjustments in the coming weeks.

**Comment by rwdaigle** [comment]
@thatkahunaguy @rpowell has done some work making the form [render well on mobile](https://github.com/spreedly/sample-payment-frame/commit/31fe73bc47494be239d9cd130d16debd76efdeeb). I hope that suffices.
