### ISSUE TITLE
Feature request: addStyleRule

### ISSUE THREAD

**Issue by ithielnor** [spreedly/sample-payment-frame#2]
Would it be possible to enable the addition of style rules to the frame? E.g. http://davidwalsh.name/add-rules-stylesheets

This would allow for support of css pseudo classes like `:focus` or `:hover`.

**Comment by rwdaigle** [comment]
Hi @ithielnor, thanks for this link. Being able to add pseudo-classes is one of our most requested features, so we definitely hear you.

Our challenge is allowing this type of flexibility while still providing a secure solution. I do believe we have a solution in the works, though it's more than a few weeks out. Stay tuned!

**Comment by isaac** [comment]
@rwdaigle - any chance you could give me a hint about what this solution might look like?

We are currently trying to implement our payment form using the iframe and we're finding it difficult to get the iframe to work with our form design. Not looking for any guarantees - just a little hope :)

**Comment by rwdaigle** [comment]
@isaac sure. We're basically looking at providing a solution where each field (card number and cvv) are their own iframes and would only contain the one field. This has the advantage of allowing you to place each field wherever you want as well as keeping all labels, tooltips etc... outside the iFrame and in your complete control. We believe this will be a much less limiting solution than what's currently in place.

**Comment by galenking** [comment]
Thanks @rwdaigle. Any idea when this might be ready?

**Comment by rwdaigle** [comment]
@galenking some idea, but we haven't been able to formally put it on our dev schedule so I'm not going to commit to anything here :)

We're just as excited about it as you are since it reduces our support burden, so rest-assured, our interests are aligned! We'll drop a note here when we have something to share.

**Comment by isaac** [comment]
Thanks @rwdaigle!

Please let me know if you ever need testers for this feature.

So with this solution you're looking at would it be possible to target the iframe inputs with `input:focus` CSS?

If this is not possible for security reasons another potential way for us to style inputs on focus would be to expose "focus" and "blur" javascript events for each input.

**Comment by galenking** [comment]
@rwdaigle, in the meantime, I wonder if you could remove the :focus styling that puts the grey halo around the input fields? Or is there a purpose to this styling that I am missing?

**Comment by rwdaigle** [comment]
@isaac 

> If this is not possible for security reasons another potential way for us to style inputs on focus would be to expose "focus" and "blur" javascript events for each input

Yes, this is the approach we will be taking.

@galenking 

> I wonder if you could remove the :focus styling that puts the grey halo around the input fields? Or is there a purpose to this styling that I am missing?

I believe that styling is browser-dependent? I.e. I don't believe we're adding that ourselves.

**Comment by isaac** [comment]
Thanks @rwdaigle - sounds good!

**Comment by mrezentes** [comment]
@ithielnor, @galenking, @isaac
Our newest release, iFrame v0.10, is implemented as two independent credit card fields (one for the number and one for the CVV) beneath a unified API. This lets you place them wherever you want on your form as they are no longer forced to be physically near each other. This also lets you keep the field labels and any other validation adornments on the master page under your full control. Custom web fonts, credit card branding images, and validation messages are now in the purview of the master page.

We encourage all users of previous iFrame versions to upgrade to v0.10 and anybody looking to limit their PCI exposure while still retaining a custom UI to try iFrame v0.10. Full documentation is available here: https://docs.spreedly.com/guides/adding-payment-methods/iframe_0_10/ . If you have any issues, please contact us at support@spreedly.com.
